---
streamlit:
  title: "MSFT - LLM assistant"
  tab_title: "LLM assistant"
  logo: "./streamlit_app/images/Microsoft_logo.png"
  page_icon: "./streamlit_app/images/Microsoft_logo.png"
  avatar: "./streamlit_app/images/openai.png"
  assistant_intro_message: "Hi there :wave:, I'm an AI assistant. I can look up information through a database of documents to answer your questions."
  about: "A demo of an AI assistant. Powered by Azure OpenAI Large Language Models and search using native vector search capabilities on PostGres, authors: Azure Data/Applied AI team"
azure:
  dummy: "test"